# Generated by Django 5.2.7 on 2025-10-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
