name: CI/CD Pipeline - Lacrei Saúde

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Export Django SECRET_KEY
        run: echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV

      # - name: Run lint
      #   run: poetry run flake8 apps

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: poetry run pytest --maxfail=1 --disable-warnings -q
