name: CI/CD Pipeline - Lacrei Saúde

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction --no-ansi

      # - name: Run lint
      #   run: poetry run flake8 apps

      - name: Run tests
        run: poetry run pytest --maxfail=1 --disable-warnings -q

      - name: Zip project for deployment
        if: github.ref == 'refs/heads/master'
        run: zip -r deploy.zip . -x "*.git*" "__pycache__/*" "*.pytest_cache/*"

      - name: Deploy to AWS Elastic Beanstalk
        if: github.ref == 'refs/heads/master'
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: lacrei-saude-api
          environment_name: lacrei-saude-prod
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_number }}
          deployment_package: deploy.zip
